name: check-go-mod

on:
  workflow_call:
    inputs:
      runs-on:
        description: An expression indicating which kind of runners to use.
        required: true
        type: string
      repository-name:
        required: true
        type: string
    secrets:
      elevated-github-token:
        required: true
jobs:
  check-go-mod:
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    # NOTE: This step is specifically needed for ENT. It allows us to access the required private HashiCorp repos.
    - name: Setup Git
      if: ${{ endsWith(inputs.repository-name, '-enterprise') }}
      run: git config --global url."https://${{ secrets.elevated-github-token }}:@github.com".insteadOf "https://github.com"
    - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version-file: 'go.mod'
    - run: go mod tidy
    - run: |
        if [[ -n $(git status -s) ]]; then
          echo "Git directory has changes"
          git status -s
          exit 1
        fi
    - name: Notify Slack
      if: ${{ failure() }}
      run: .github/scripts/notify_slack.sh
